# Theme color for customize
# Notice: color value must in double quotes like "#000" or may cause error!
# ---------------
theme_color:
  enable: true
  main: "#FF667B"
  paginator: "#FF667B"
  button_hover: "#FF667B"
  text_selection: "#FF667B"
  link_color: "#FF667B"
  hr_color: "#FF667B"

# Main menu navigation
# ---------------
menu:
  Home: /
  Archives: /archives
  Tags: /tags
  Categories: /categories
  #XXX: /xxx

# Favicon
# use my-favicon.ico to avoid duplicate favicon of melody theme
# ---------------
favicon: /img/my-favicon.ico

# PWA
# See https://github.com/JLHwung/hexo-offline
# ---------------
pwa:
  enable: true
  manifest: /manifest.json
  # If you don't want to trouble, just ignore the following things
  # See https://realfavicongenerator.net/
  theme_color: "#FF667B"
  apple_touch_icon: /apple-touch-icon.png
  favicon_32_32: /favicon-32x32.png
  favicon_16_16: /favicon-16x16.png
  mask_icon: /safari-pinned-tab.svg


# Highlight theme
# ---------------
highlight_theme: light

# code_word_wrap: true or false

# Nav settings
# ---------------
social:
  github: https://github.com/Zakariyya
  weibo: https://weibo.com/1950891577/profile?topnav=1&wvr=6
  # facebook-f: facebook.com

# Algolia search
# ---------------
algolia_search:
  enable: false
  # hits:
  #   per_page: 10

# Local search
# Please see doc for more details: https://molunerfinn.com/hexo-theme-melody-doc/#/third-party-support?id=local-search
# ---------------
local_search:
  enable: false

# MathJax
# Please see doc for more details: https://molunerfinn.com/hexo-theme-melody-doc/#/third-party-support?id=mathjax
# ---------------
mathjax:
  enable: false
  cdn: https://cdn.jsdelivr.net/npm/mathjax/MathJax.js?config=TeX-AMS-MML_HTMLorMML


# Toggle fireworks (IE >= 10)
# ---------------
fireworks: false

# Analysis
# ---------------
baidu_analytics: 

google_analytics: UA-123397569-1

# Tencent_analytics ID
tencent_analytics: 

# stylesheets loaded in the <head>
# ---------------
stylesheets:
- /css/index.css

# scripts loaded in the end of the body
# ---------------
scripts:
- /js/utils.js
- /js/fancybox.js
- /js/sidebar.js
- /js/copy.js
- /js/fireworks.js
- /js/transition.js
- /js/scroll.js
- /js/head.js

# cdn for third-party library
# ---------------
cdn:
  css:
    fontawesome: https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css
  js:
    anime: /js/third-party/anime.min.js
    jquery: /js/third-party/jquery.min.js
    fancybox: /js/third-party/jquery.fancybox.min.js
    velocity: /js/third-party/velocity.min.js 
    velocity-ui: /js/third-party/velocity.ui.min.js 

# Post info settings
# ---------------
avatar: https://avatars2.githubusercontent.com/u/14139937?s=460&v=4

top_img: /img/top.jpg # false or url of img 

post_meta:
  date_type: created # created or updated 
  categories: true
  tags: true

# Please see doc for more details: https://molunerfinn.com/hexo-theme-melody-doc/#/additional-package-support?id=word-counting
wordcount:
  enable: true

toc:
  enable: true
  number: true

post_copyright:
  enable: true
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

# Please see doc for more details: https://molunerfinn.com/hexo-theme-melody-doc/#/theme-config?id=auto-excerpt
auto_excerpt:
  enable: true
  length: 50

# slide
# For reveal.js config, see https://github.com/hakimel/reveal.js#configuration
slide:
  separator: ---
  separator_vertical: --
  charset: utf-8
  theme: black
  # optional
  mouseWheel: false
  transition: slide
  transitionSpeed: default
  parallaxBackgroundImage: ''
  parallaxBackgroundSize: ''
  parallaxBackgroundHorizontal: null
  parallaxBackgroundVertical: null

# QR_code:
  # - itemlist:
  #     img:
  #     text:

# adv:
  # enable: false
  # info: 

# Share System
# ---------------
addThis:
  enable: false
  #pubid: 

sharejs:
  enable: true
  disabled_sites: 

# Comments System
# ---------------
disqus:
  enable: true
  shortname: H2O2
  count: true

# laibili:
  # enable: false
  # uid:

# gitment
  # enable: false
  # owner: 
  # repo: 
  # client_id: 
  # client_secret: 

# gitalk:
#   enable: false
#   client_id: 
#   client_secret: 
#   repo:
#   owner:
#   admin:
####   Using this js for redirect to gitalk container after login
####   See https://github.com/gitalk/gitalk/issues/125
#   js: https://cdn.jsdelivr.net/gh/upupming/gitalk@36368e5dffd049e956cdbbd751ff96c28d8255cf/dist/gitalk.min.js

# valine comment system. https://valine.js.org
# valine:
#   enable: true # if you want use valine,please set this value is ture
#   appId:  MMdsKHHea0L1GyGfUI1Ypz3P-gzGzoHsz # leancloud application app id
#   appKey: UVgr8oUHNNPiEhvXQ1oF9czo # leancloud application app key
#   notify: false # valine mail notify (true/false) https://github.com/xCss/Valine/wiki
#   verify: false # valine verify code (true/false)
#   pageSize: 10 # comment list page size
#   avatar:  # gravatar style https://valine.js.org/#/avatar
#   lang: zh-cn # i18n: zh-cn/en
#   placeholder: Just go go # valine comment input placeholder(like: Please leave your footprints )
#   guest_info: nick,mail,link #valine comment header inf

# Footer Settings
# ---------------
since: 2015

# footer_custom_text:

ICP:
  enable: false
  #text: 

# busuanzi count for PV / UV in site
busuanzi:
  # count values only if the other configs are false
  enable: true
  # custom uv span for the whole site
  site_uv: true
  site_uv_header: <i class="fa fa-user"></i>
  site_uv_footer:
  # custom pv span for the whole site
  site_pv: true
  site_pv_header: <i class="fa fa-eye"></i>
  site_pv_footer:
  # custom pv span for one page only
  page_pv: true
  page_pv_header: <i class="fa fa-file-o"></i>
  page_pv_footer:


# Sidebar Settings
# ---------------
links_title: Links
links:
  厦门大学数据库实验室: http://dblab.xmu.edu.cn/blog/category/big-data/
  四点网: http://4dian.sinaapp.com/

# Follow Me Button
follow:
  enable: true
  url: 'https://github.com/Zakariyya'
  text: 'Follow Me'
